#ifndef _POQUE_GEOMETRIC_H_
#define _POQUE_GEOMETRIC_H_

extern PoqueValueHandler point_val_handler;
extern PoqueValueHandler line_val_handler;
extern PoqueValueHandler lseg_val_handler;
extern PoqueValueHandler path_val_handler;
extern PoqueValueHandler box_val_handler;
extern PoqueValueHandler polygon_val_handler;
extern PoqueValueHandler circle_val_handler;

extern PoqueValueHandler pointarray_val_handler;
extern PoqueValueHandler linearray_val_handler;
extern PoqueValueHandler lsegarray_val_handler;
extern PoqueValueHandler patharray_val_handler;
extern PoqueValueHandler boxarray_val_handler;
extern PoqueValueHandler polygonarray_val_handler;
extern PoqueValueHandler circlearray_val_handler;

#endif
